# floorplan_conv.tcl (v2: XDC method)
#
# 1차 시도 실패 원인: open_project 직후엔 design 이 없어 get_cells 가 동작 안 함.
# 해결: Pblock 정의를 pblock_conv.xdc 로 작성 → constrs_1 에 추가 →
#       USED_IN_IMPLEMENTATION true 로 등록 → impl 의 link_design 시점에 평가.
# 효과: TCL 자체는 단순해지고, 다음 impl 들에도 자동 적용 (제거하려면 XDC 파일만 빼면 됨).
#
# 실행: vivado -mode batch -source floorplan_conv.tcl -log floorplan_conv.log

set XPR {Z:/2026 CAU/AIX2026/git/Yolo_Accelerator/yolohw/fpga/IP_PACKAGING/fpga_yolohw/fpga_yolohw.xpr}
set XDC {Z:/2026 CAU/AIX2026/git/Yolo_Accelerator/yolohw/fpga/IP_PACKAGING/fpga_yolohw/pblock_conv.xdc}

puts "=========================================="
puts "  Floorplan: pblock_conv via XDC"
puts "=========================================="

open_project $XPR
puts "=== Project: [current_project] ==="
puts "=== Runs:    [get_runs] ==="

# ---- 1. pblock_conv.xdc 작성 ----------------------------------------
set fp [open $XDC w]
puts $fp "# pblock_conv (auto-generated by floorplan_conv.tcl)"
puts $fp "# Goal: shrink route on 'conv_phase_r -> u_line_buf BRAM addr' (-0.183ns @81.25MHz)"
puts $fp ""
puts $fp "create_pblock pblock_conv"
puts $fp "add_cells_to_pblock \[get_pblocks pblock_conv\] \[get_cells \{system_i/yolo_engine_0/inst/u_conv system_i/yolo_engine_0/inst/u_line_buf\}\]"
puts $fp "resize_pblock \[get_pblocks pblock_conv\] -add \{CLOCKREGION_X0Y1:CLOCKREGION_X1Y2\}"
puts $fp "set_property IS_SOFT FALSE \[get_pblocks pblock_conv\]"
close $fp
puts "=== XDC written: $XDC ==="

# ---- 2. XDC 를 프로젝트에 등록 (impl-only) --------------------------
# NOTE: $XDC 경로에 공백("2026 CAU") 포함 → add_files / get_files 인자에
#       반드시 [list $XDC] 로 wrap 해야 single token 으로 인식됨.
set xdc_files [get_files -quiet pblock_conv.xdc]
if {[llength $xdc_files] == 0} {
    add_files -fileset constrs_1 -norecurse [list $XDC]
    puts "=== XDC added to constrs_1 ==="
} else {
    puts "=== XDC already in project: $xdc_files ==="
}
# 파일명만으로 조회 (공백 회피, constrs_1 안에서 unique)
set xdc_obj [get_files pblock_conv.xdc]
set_property USED_IN_SYNTHESIS      false $xdc_obj
set_property USED_IN_IMPLEMENTATION true  $xdc_obj
set_property PROCESSING_ORDER       LATE  $xdc_obj
puts "=== XDC properties set on: $xdc_obj ==="

# ---- 3. impl_1 재실행 (synth 캐시 유지) -----------------------------
puts "=== reset_run impl_1 ==="
reset_run impl_1

puts "=== launch_runs impl_1 -to_step write_bitstream -jobs 8 ==="
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# ---- 4. 리포트 -------------------------------------------------------
set status [get_property STATUS [get_runs impl_1]]
puts "=== impl_1 STATUS: $status ==="

if {[catch {open_run impl_1} msg]} {
    puts "ERROR: open_run impl_1 failed: $msg"
} else {
    report_timing_summary -file timing_summary_floorplan.rpt
    report_utilization -pblocks [get_pblocks pblock_conv] -file pblock_conv_util.rpt
}

set wns [get_property STATS.WNS [get_runs impl_1]]
set tns [get_property STATS.TNS [get_runs impl_1]]
set whs [get_property STATS.WHS [get_runs impl_1]]
puts "=========================================="
puts "  FINAL  WNS = $wns ns"
puts "         TNS = $tns ns"
puts "         WHS = $whs ns"
puts "  impl_1 status: $status"
puts "=========================================="
exit
