# pblock_conv (auto-generated by floorplan_conv.tcl)
# Goal: shrink route on 'conv_phase_r -> u_line_buf BRAM addr' (-0.183ns @81.25MHz)

create_pblock pblock_conv
add_cells_to_pblock [get_pblocks pblock_conv] [get_cells {system_i/yolo_engine_0/inst/u_conv system_i/yolo_engine_0/inst/u_line_buf}]
resize_pblock [get_pblocks pblock_conv] -add {CLOCKREGION_X0Y1:CLOCKREGION_X1Y2}
set_property IS_SOFT FALSE [get_pblocks pblock_conv]
